services:
  frontend:
    build:
      context: ./frontend
    ports:
       - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - library
    restart: on-failure
    command: ["./wait-for-it.sh", "library:5432", "--", "npm", "start"]

  library:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - library_data:/var/lib/postgresql/data

volumes:
  library_data:
